export ZDOTDIR="$HOME"/.config/zsh 

export PATH="$PATH:/home/gpoeta/.local/bin"

# config XDG
# exportamos variables de entorno para el XDG estandar
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

# exportamos varibles nuevas de los dotfiles
export HISTFILE="$XDG_STATE_HOME"/zsh/history
#compinit -d "$XDG_CACHE_HOME"/zsh/zcompdump-"$ZSH_VERSION" # No funciona?
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker 
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo

# alias para xdg
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts" 

# a partir de ahora solo se exportaran sin orden aca
export GOPATH="$XDG_DATA_HOME"/go
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history 